username = input('Введите имя пользователя:')
title = []
result=title.append(input('Введите заголовок заметки:'))
result2=title.append(input('Введите заголовок заметки:'))
result3=title.append(input('Введите заголовок заметки:'))
content = input('Введите описание заметки:')
status = input('Введите статус заметки:')
created_date = input('Введите дату создания заметки в формате "день-месяц-год" пример 01-01-2001:')
issue_date = input('Введите дату истечения заметки (дедлайн) в формате "день-месяц-год" пример 01-01-2001:')
print('Имя пользователя:', username)
print('Заголовоки заметки:', '\n1.', title[0], '\n2.', title[1], '\n3.', title[2])
print('Описание заметки:', content)
print('Статус заметки:', status)
print(f'Дата создания заметки, {created_date[:-5]}')
print(f'Дедлайн, {issue_date[:-5]}')
